services:
 backend:
  build: .
  volumes:
   - .:/app
  ports:
   - "8000:8000"
  env_file:
   - .env
  depends_on:
   - db

 db:
  image: postgres
  restart: always
  environment:
   POSTGRES_DB: ozon
   POSTGRES_USER: ozon_user
   POSTGRES_PASSWORD: admin
  ports:
   - "5432:5432"
  volumes:
   - postgres_data:/var/lib/postgressql/data
volumes:
 postgres_data: