services:
 backend:
  build: .
  volumes:
   - .:/app
  ports:
   - "8000:8000"
  env_file:
   - .env
  depends_on:
   - db
   - redis
  command: sh ./entrypoint.sh

 worker:
  build: .
  volumes:
   - .:/app
  env_file:
   - .env
  depends_on:
   - db
   - redis
  command: celery -A config worker --loglevel=info
 test:
  build: .
  volumes:
   - .:/app
  env_file:
   - .env
  depends_on:
   - db
   - redis
  command: pytest --disable-warnings --maxfail=3
 redis:
  image: redis
  ports:
   - "6379:6379"

 db:
  image: postgres
  restart: always
  environment:
   POSTGRES_DB: ozon
   POSTGRES_USER: ozon_user
   POSTGRES_PASSWORD: admin
  ports:
   - "5432:5432"
  volumes:
   - postgres_data:/var/lib/postgressql/data
volumes:
 postgres_data: